# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
stages:
    - test
    - sonarqube-check

test: 
    stage: test
    image: python:3.8.3
    # Pick zero or more services to be used on all builds.
    # Only needed when using a docker container to run your tests in.
    # Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: django
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/django"
    # This folder is cached between builds
    # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
    cache:
        paths:
        - ~/.cache/pip/
    script:
        - python3.8 -V # Print out python version for debugging
        - pip install pipenv
        - pipenv install --dev
        - pipenv run python manage.py migrate
        - pipenv run python manage.py test
        - pipenv run coverage run -m pytest
        #- pipenv run coverage run report

sonarqube-check:
    stage: sonarqube-check
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    script:
        - sonar-scanner -Dsonar.qualitygate.wait=true
    allow_failure: true
  